[package]
name = "rascal"
version = "0.0.1"
edition = "2021"
authors = ["Ricardo da Rocha Vitor"]
description = "A minimalist script programming language inspired by Pascal and Whispem writen in rust"
license = "MIT"
repository = "https://github.com/ricardodarocha/rascal"
keywords = ["interpreter", "language", "minimalist", "educational", "pascal"]
categories = ["compilers"]

[dependencies]
